---
- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
  when: force_upgrade == True

- name: Import gpg key for HashiCorp repository
  apt_key:
    url: "{{ hashicorp.apt_key }}"
    state: present

- name: Add HashiCorp official repository
  apt_repository:
    repo: "deb [arch=amd64] {{ hashicorp.repo }} focal main"
    state: present

- name: Update apt package index
  apt:
    update_cache: yes
  changed_when: no

- name: Install common packages using apt
  apt:
    name: "{{ common_packages_apt | default([]) }}"
    state: present

- name: Install common packages using snap
  snap:
    name: "{{ common_packages_snap | default([]) }}"
    state: present

- name: Install common packages using snap with option '--classic'
  snap:
    name: "{{ common_packages_snap_classic | default([]) }}"
    classic: yes
    state: present

- name: Create symlink diff-highlight
  file:
    src: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
    dest: /usr/local/bin/diff-highlight
    owner: root
    group: root
    mode: 0755
    state: link
