---
- name: Add resolved config file
  template:
    src: etc/systemd/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-resolved
