---
- name: Add systemd-timesyncd config file
  template:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-timesyncd
