---
- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: restarted
    enabled: yes
  become: yes

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved.service
    state: restarted
    enabled: yes
  become: yes
