---
- name: Install anyenv system-wide
  git:
    repo: "{{ anyenv.git_repo }}"
    dest: "{{ anyenv.install_dir }}"

- name: Install anyenv plugins
  git:
    repo: "{{ item.git_repo }}"
    dest: "{{ anyenv.install_dir }}/plugins/{{ item.name }}"
  with_items: "{{ anyenv.plugins | default([]) }}"

- name: Initialize anyenv
  command: anyenv install --force-init
  args:
    creates: "{{ anyenv.definition_root }}"
  environment:
    PATH: "{{ anyenv.install_dir }}/bin:{{ ansible_env.PATH }}"
